### ISSUE TITLE
checker not recognizing dots in logograms

### ISSUE THREAD

**Issue by JacobLauinger** [oracc/editing#9]
Starting yesterday, I noticed that the checker is not recognizing the dots in logograms; e.g, it reads KU₃.BABBAR as KU₃BABBAR.  And then, I suppose since it can't find a form KU₃BABBAR in the glossary, the relevant links are all dead on the web interface.

FWIW, since we are using legacy data, our transliterations also separate logographic suffixes from logograms with a dot instead of a dash, and these dots are also disappearing for the checker.

**Comment by stinney** [comment]
This should be fixed as of this afternoon Munich time.  Could you check it?

Thanks,

Steve

-------- Original Message --------

**Comment by JacobLauinger** [comment]
Ok, just checked - the compound logograms with dots do now appear as live links on the web interface, but when I click on them, I get the "No HTML file found ...." message.

Also, all of the glossaries have disappeared from the hub page.

**Comment by stinney** [comment]
Hi, Jake--I see you just did an oracc check and perhaps you fixed some issues; I just rebuilt aemw/amarna and the glossaries are there on the hub page and clicking on words with determinatives does reach a glossary entry.

Thanks for reporting the issues here--if you can include the affected project and a specific example that is often helpful, too.

**Comment by JacobLauinger** [comment]
Hi Steve -   It wasn't me who fixed any issues - the checker just started returning no errors.  Anyway, yes, everything seems great now, thank you so much!

I am going to go ahead and bump the thread I started earlier about the web interface attributing incorrect senses since it is still an issue and in case it is connected to what was happening with the dots.  I will be sure to include screenshots :)
